<a href="https://colab.research.google.com/github/Edutroy/Numpy-and-Pandas/blob/main/NumpyII.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inicio con NumPy**



In [26]:
import numpy as np


#generate some random data
data=np.random.randn(3,3,2)
print('Array random :')
data


Array random :


array([[[ 2.53696198,  0.06437189],
        [ 0.5561876 ,  0.1590073 ],
        [ 0.23897446,  1.09739413]],

       [[ 1.77331381,  0.22467746],
        [-0.82742978, -0.52248687],
        [-2.88466005,  1.27160548]],

       [[-0.38127137,  1.08579367],
        [ 0.53360748,  1.09647011],
        [ 1.07665634,  1.30881315]]])

In [16]:
#amth operation with arrays
data*10

array([[[ -4.79854759,   4.28109583],
        [ -8.28080598,  18.60036619],
        [ -7.33351001,   3.49352788]],

       [[ -0.60876706,  -9.83224914],
        [ -8.31288139, -16.21296336],
        [ -1.18246045, -14.89913002]]])



> Creating arrays



In [ ]:
lista =[1,2,3,4,5,6,7,8,9]
lista
arr = np.array(lista)
arr
type(arr)

numpy.ndarray

In [ ]:
data =[[1,2,3,4], [5,6,7,8]]
arr2=np.array(data)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
data2 =[[[1,2,3,4], [5,6,7,8]] ,[[10,11,12,13], [14,15,16,17]]]
arr3=np.array(data2)
arr3


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]]])

while array_name.dim we see:

*(number of dimensions)*

In [ ]:
print(arr2.ndim)
arr3.ndim

2


3

We see this with array-name.shape:

*(row, colums)*



In [ ]:
print(arr2.shape)
arr3.shape

(2, 4)


(2, 2, 4)

>Indexing

In [ ]:
names =np.array()

> Agreganndo y Eliminando dimensiones



In [ ]:
vector = np.array([1, 2, 3,5,6,7], ndmin = 10)
print(vector) 
vector.ndim 

[[[[[[[[[[1 2 3 5 6 7]]]]]]]]]]


10

In [ ]:
test=np.array([1, 2, 3])
print(test)
print(test.ndim) 
print(test.shape)
print('################')
expand = np.expand_dims( test , axis = 1)
print(expand)
print(expand.ndim) 
expand.shape

[1 2 3]
1
(3,)
################
[[1]
 [2]
 [3]]
2


(3, 1)

In [ ]:
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)#Elimina las dimesiones que no se utilizan
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3 5 6 7]]]]]]]]]] 10
[1 2 3 5 6 7] 1


Arrays


In [3]:
print(np.arange(0,15))#crea un array desde las posionces indicadas
np.arange(0,20,2)#los alterna dependiendo la cantiad que queramos

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
print(np.zeros(10))
np.ones((5,5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.eye(5)#crea matriz identidd

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])