<a href="https://colab.research.google.com/github/Edutroy/Numpy-and-Pandas/blob/main/NumpyII.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inicio con NumPy**



In [1]:
import numpy as np


#generate some random data
data=np.random.randn(3,3,2)
print('Array random :')
data


Array random :


array([[[-0.56401124, -0.87747484],
        [ 2.14884474, -1.06826199],
        [-0.54231663,  0.26650691]],

       [[ 0.76298825, -1.63898292],
        [-0.36391812, -1.0467189 ],
        [-0.14463764,  2.33902979]],

       [[ 0.37358671,  0.9398292 ],
        [-0.61824345,  1.01750594],
        [ 0.2939203 ,  1.70226091]]])

In [2]:
#amth operation with arrays
data*10

array([[[ -5.64011239,  -8.77474844],
        [ 21.48844743, -10.68261988],
        [ -5.42316632,   2.66506914]],

       [[  7.62988255, -16.38982916],
        [ -3.63918115, -10.46718904],
        [ -1.44637645,  23.39029788]],

       [[  3.73586706,   9.39829204],
        [ -6.18243449,  10.17505939],
        [  2.93920295,  17.02260912]]])



> Creating arrays



In [3]:
lista =[1,2,3,4,5,6,7,8,9]
lista
arr = np.array(lista)
arr
type(arr)

numpy.ndarray

In [4]:
data =[[1,2,3,4], [5,6,7,8]]
arr2=np.array(data)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
data2 =[[[1,2,3,4], [5,6,7,8]] ,[[10,11,12,13], [14,15,16,17]]]
arr3=np.array(data2)
arr3


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]]])

while array_name.dim we see:

*(number of dimensions)*

In [6]:
print(arr2.ndim)
arr3.ndim

2


3

We see this with array-name.shape:

*(row, colums)*



In [7]:
print(arr2.shape)
arr3.shape

(2, 4)


(2, 2, 4)

>Indexing

In [10]:
names =np.array()

> Agreganndo y Eliminando dimensiones



In [11]:
vector = np.array([1, 2, 3,5,6,7], ndmin = 10)
print(vector) 
vector.ndim 

[[[[[[[[[[1 2 3 5 6 7]]]]]]]]]]


10

In [12]:
test=np.array([1, 2, 3])
print(test)
print(test.ndim) 
print(test.shape)
print('################')
expand = np.expand_dims( test , axis = 1)
print(expand)
print(expand.ndim) 
expand.shape

[1 2 3]
1
(3,)
################
[[1]
 [2]
 [3]]
2


(3, 1)

In [13]:
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)#Elimina las dimesiones que no se utilizan
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3 5 6 7]]]]]]]]]] 10
[1 2 3 5 6 7] 1


Arrays


In [14]:
print(np.arange(0,15))#crea un array desde las posionces indicadas
np.arange(0,20,2)#los alterna dependiendo la cantiad que queramos

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
print(np.zeros(10))
np.ones((5,5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.eye(5)#crea matriz identidd

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Reshape


In [22]:
arr = np.random.randint(1,10,(3,2))
print(arr)
print(arr.shape)
print('Cambiando con reshape')
print(arr.reshape(1,6))
print('En  C')
print(np.reshape(arr,(2,3), 'C'))
print('En  Fortran')
print(np.reshape(arr,(2,3), 'F'))

[[6 6]
 [4 2]
 [3 5]]
(3, 2)
Cambiando con reshape
[[6 6 4 2 3 5]]
En  C
[[6 6 4]
 [2 3 5]]
En  Fortran
[[6 3 2]
 [4 6 5]]
