<a href="https://colab.research.google.com/github/Edutroy/Numpy-and-Pandas/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inicio con NumPy**



In [18]:
import numpy as np


#generate some random data
data=np.random.randn(2, 3)
print('Array random :')
data


Array random :


array([[ 0.40485243, -2.63327161, -0.04350825],
       [ 0.44743702,  0.71953462,  0.05032043]])

In [21]:
#amth operation with arrays
data*10

array([[  4.04852427, -26.33271611,  -0.43508253],
       [  4.47437024,   7.19534622,   0.50320428]])



> Creating arrays



In [20]:
lista =[1,2,3,4,5,6,7,8,9]
lista
arr = np.array(lista)
arr
type(arr)

numpy.ndarray

In [36]:
data =[[1,2,3,4], [5,6,7,8]]
arr2=np.array(data)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
data2 =[[[1,2,3,4], [5,6,7,8]] ,[[10,11,12,13], [14,15,16,17]]]
arr3=np.array(data2)
arr3


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]]])

while array_name.dim we see:

*(number of dimensions)*

In [41]:
print(arr2.ndim)
arr3.ndim

2


3

We see this with array-name.shape:

*(row, colums)*



In [42]:
print(arr2.shape)
arr3.shape

(2, 4)


(2, 2, 4)