<a href="https://colab.research.google.com/github/Edutroy/Numpy-and-Pandas/blob/main/NumpyII.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inicio con NumPy**



In [ ]:
import numpy as np


#generate some random data
data=np.random.randn(2,3)
print('Array random :')
data


Array random :


array([[-0.00402115,  0.63582559,  0.31551742],
       [ 2.08655849, -0.29357103,  0.89292038]])

In [ ]:
#amth operation with arrays
data*10

array([[-0.04021154,  6.3582559 ,  3.1551742 ],
       [20.86558489, -2.93571029,  8.92920379]])



> Creating arrays



In [ ]:
lista =[1,2,3,4,5,6,7,8,9]
lista
arr = np.array(lista)
arr
type(arr)

numpy.ndarray

In [ ]:
data =[[1,2,3,4], [5,6,7,8]]
arr2=np.array(data)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
data2 =[[[1,2,3,4], [5,6,7,8]] ,[[10,11,12,13], [14,15,16,17]]]
arr3=np.array(data2)
arr3


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]]])

while array_name.dim we see:

*(number of dimensions)*

In [ ]:
print(arr2.ndim)
arr3.ndim

2


3

We see this with array-name.shape:

*(row, colums)*



In [ ]:
print(arr2.shape)
arr3.shape

(2, 4)


(2, 2, 4)

>Indexing

In [ ]:
names =np.array()

> Agreganndo y Eliminando dimensiones



In [ ]:
vector = np.array([1, 2, 3,5,6,7], ndmin = 10)
print(vector) 
vector.ndim 

[[[[[[[[[[1 2 3 5 6 7]]]]]]]]]]


10

In [ ]:
test=np.array([1, 2, 3])
print(test)
print(test.ndim) 
print(test.shape)
print('################')
expand = np.expand_dims( test , axis = 1)
print(expand)
print(expand.ndim) 
expand.shape

[1 2 3]
1
(3,)
################
[[1]
 [2]
 [3]]
2


(3, 1)

In [ ]:
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)#Elimina las dimesiones que no se utilizan
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3 5 6 7]]]]]]]]]] 10
[1 2 3 5 6 7] 1
